### ISSUE TITLE
About Python Files

### ISSUE THREAD

**Issue by lzh-pro666** [adbrei/RENarGen#1]
Hello, your work is very meaningful. May I ask if you can provide the run_clm_no-trainer.py file？

**Comment by adbrei** [comment]
We used the script provided by HuggingFace. The most recent version of the file can be found [here](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm_no_trainer.py).

**Comment by lzh-pro666** [comment]
Thank you for your reply！！！May I ask if it is possible to provide the run_clm_no-rainer.py file that you are using? Currently, the newer run_clm_no-rainer.py file does not include the -- testfile parameter
